
project:
  name: pdf-element
  description: Polymer element to render PDF documents

markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)

exclude: ['README.md', 'LICENSE']
