
project:
  name: pdf-element
  description: Polymer 1.0 component to render PDF

markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)

exclude: ['README.md', 'LICENSE']
